name: Elting Lab Research
description: Science updates from the Elting Lab at NCSU
url: http://www4.ncsu.edu
baseurl: /~mmwillia

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough
