name: Elting Lab Research
description: Science updates from the Elting Lab at NCSU
url: http://ncsu.edu

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

